// svelte/src/App.svelte
<script lang="ts">
  import * as d3 from "d3";

  // import LineChart from "./lib/LineChart.svelte";
  import ReusableLineChart from "./lib/ReusableLineChart.svelte";

  import type { WeatherData, BoundedDimensions } from "./types";

  //* Step 1a. Fetch Data
  async function promise() {
    const res = await d3.json<WeatherData[]>("/data/my_weather_data.json")
    return res;
  }

  const fetchData = promise();

  //* Step 2. Create chart dimensions
  const dimensions: BoundedDimensions = {
    width: window.innerWidth * 0.9,
    height: 400,
    margin: {
      top: 15,
      right: 15,
      bottom: 40,
      left: 60,
    },
    boundedWidth: 0,
    boundedHeight: 0,
  };

  dimensions.boundedWidth =
    dimensions.width - dimensions.margin.left - dimensions.margin.right;
  dimensions.boundedHeight =
    dimensions.height - dimensions.margin.top - dimensions.margin.bottom;
</script>

{#await fetchData}
  <div>Loading data...</div>
{:then dataset} 
  <!-- <LineChart {dataset} /> -->
  <ReusableLineChart {dataset} {dimensions} metric="temperatureMax" />
{/await}

// vue/src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import { ref } from "vue";
import * as d3 from "d3";
import type { WeatherData, BoundedDimensions } from "./types";

// import LineChart from "./components/LineChart.vue";
import ReusableLineChart from "./components/ReusableLineChart.vue";

const dataset = ref<WeatherData[] | null>(null);
d3.json<WeatherData[]>("/data/my_weather_data.json").then((res) => {
  dataset.value = res ?? null;
});

//* Step 2. Create chart dimensions
const dimensions = ref<BoundedDimensions>({
  width: window.innerWidth * 0.9,
  height: 400,
  margin: {
    top: 15,
    right: 15,
    bottom: 40,
    left: 60,
  },
  boundedWidth: 0,
  boundedHeight: 0,
});

dimensions.value.boundedWidth =
  dimensions.value.width -
  dimensions.value.margin.left -
  dimensions.value.margin.right;
dimensions.value.boundedHeight =
  dimensions.value.height -
  dimensions.value.margin.top -
  dimensions.value.margin.bottom;
</script>

<template>
  <div v-if="dataset" class="wrapper">
    <!-- <LineChart :dataset="dataset" /> -->
    <ReusableLineChart
      :dataset="dataset"
      :dimensions="dimensions"
      metric="temperatureMax"
    />
  </div>
  <div v-else>Loading data...</div>
</template>
